name: Actions after push to `master` branch and deploy to sny services

on:
  push:
    branches:
      - temp
      - master
      
jobs:
  uploading:
    runs-on: macOS-latest
    timeout-minutes: 30
    steps:

    - name: Checkout pull request branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true

    - name: Add tag and push to CocoaPods trunk
      run: |
        bundle exec fastlane push_pod