name: Prepare actions before deploy project

on: 
  pull_request:
    branches:
      - '0.1.4'
      - master
      
jobs:
  testing:
    runs-on: macOS-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
    
    - name: Update `podspec` xcode-version
      run: |
        bundle exec fastlane update_podspec_version