name: Prepare actions before deploy project

on: 
  pull_request:
    branches:
      - master
      
jobs:
  testing:
    runs-on: macOS-latest
    timeout-minutes: 20
    steps:
    
    - name: Checkout pull request branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Select lates available version of Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
      
    - name: Build project for iOS
      run: |
        xcodebuild test -project AirKit.xcodeproj -scheme AirKit -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=latest' | xcpretty && exit ${PIPESTATUS[0]}

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true

    - name: Update podspec xcode-version
      run: |
        bundle exec fastlane update_podspec_version