name: Prepare actions before deploy project

on: 
  pull_request:
    branches:
      - '0.1.4'
      - master
      
jobs:
  runs-on: macOS-latest
  timeout-minutes: 20
  steps:

  - name: Test
    run: |
    echo ${{ github.event }}