name: Prepare actions before deploy project

on: 
  pull_request:
    branches:
      - '0.1.4'
      - master
      
jobs:
  runs-on: macOS-latest
  timeout-minutes: 20
  steps:

  - name: Running on a pull request branch.
    if: steps.branch-name.outputs.is_default == 'false'
    run: |
      echo "Running on pr: ${{ steps.branch-name.outputs.current_branch }}"