name: Prepare actions before deploy project

on: 
  pull_request:
    branches:
      - '0.1.4'
      - master
      
jobs:
  testing:
    runs-on: macOS-latest
    timeout-minutes: 20
    steps:
    
    - name: Checkout pull request branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - run: git checkout HEAD^