name: Prepare to deploy

on: 
  pull_request:
    branches:
      - master
    paths:
      - 'AirKit/Source/**'
      - 'AirKitTests/Source/**'
      - 'AirKitTests/Resource/**'

jobs:
  testing_iOS:
    runs-on: macOS-latest
    timeout-minutes: 10
    steps:
    
    - name: Checkout pull request branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Select lates available version of Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
      
    - name: Build project for iOS
      run: |
        xcodebuild test -project AirKit.xcodeproj -scheme AirKit -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=latest' | xcpretty && exit ${PIPESTATUS[0]}

  testing_macOS:
    runs-on: macOS-latest
    timeout-minutes: 10
    steps:
    
    - name: Checkout pull request branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Select lates available version of Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
      
    - name: Install the Apple certificate and provisioning profile
      env:
        BUILD_CERTIFICATE_BASE64: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE }}
        P12_PASSWORD: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE_PASSWORD }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        # Create variables
        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

        # Import certificate and provisioning profile from secrets
        echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH

        # Create temporary keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

        # Import certificate to keychain
        security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH

    - name: Build project for macOS
      run: |
        xcodebuild test -project AirKit.xcodeproj -scheme AirKit -destination 'platform=macOS' | xcpretty && exit ${PIPESTATUS[0]}

  checking_linter:
    runs-on: macOS-latest
    timeout-minutes: 5
    steps:

    - name: Checkout pull request branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Check Pod linter
      run: |
        pod lib lint AirKit.podspec