name: Build project and run unit tests

on: 
  pull_request

jobs:
  testing:
    runs-on: macOS-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install Cocoa Pods dependencies
      run: pod install --repo-update
    
    - uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        workspace: AirKit.xcworkspace
        scheme: AirKit
        destination: platform=iOS Simulator
        action: test

    # - name: Run unit tests
    #   run: xcodebuild test -scheme AirKit -workspace AirKit.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=latest' | xcpretty --color && exit ${PIPESTATUS[0]}
