name: Build project and run unit tests

on: 
  pull_request

jobs:
  testing:
    runs-on: macOS-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install Cocoa Pods dependencies
      run: pod install --repo-update
        
    - name: Run unit tests
      run: xcodebuild test -scheme AirKit -workspace AirKit.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' | xcpretty && exit ${PIPESTATUS[0]}
