name: Prepare to deploy

on: 
  push:
    branches:
      - 'rc/**'
    paths:
      - AirKit.xcodeproj/project.pbxproj

jobs:
  testing:
    runs-on: macOS-latest
    timeout-minutes: 5
    steps:
    
    - name: Checkout pull request branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true

    - name: Update podspec xcode-version
      run: |
        bundle exec fastlane update_podspec_version